config/routes.rb
Retreat::Application.routes.draw do

  root :to => 'families#welcome'

  resources :volunteer_tasks

  root :to => 'families#new'
  resources :food_items
  resources :food_promises

  get "food_committee/index"
  get "registrar/show"

  resources :families do
    resources :people
    collection do 
      put :paid
    end
  end

  resources :people
  
  resource :food_committee, :controller => :food_committee
  resource :retreat_committee, :controller => :retreat_committee
  resource :childcare, :controller => :childcare
  resource :registrar, :controller => :registrar
  
  get "static_pages/info"
  get "static_pages/schedule"

end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  attr_accessible :description, :requested
  has_many :food_promises
  has_many :families, :through => :food_promises
  
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @food_items }
    end
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
    @food_item = FoodItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food_item }
    end
  end

  # GET /food_items/new
  # GET /food_items/new.json
  def new
    @food_item = FoodItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food_item }
    end
  end

  # GET /food_items/1/edit
  def edit
    @food_item = FoodItem.find(params[:id])
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(params[:food_item])

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to "http://retreat.herokuapp.com/food_committee", notice: 'Food item was successfully created.' }
        
      else
        format.html { render action: "new" }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /food_items/1
  # PUT /food_items/1.json
  def update
    @food_item = FoodItem.find(params[:id])

    respond_to do |format|
      if @food_item.update_attributes(params[:food_item])
        format.html { redirect_to "http://retreat.herokuapp.com/food_committee", notice: 'Food item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item = FoodItem.find(params[:id])
    @food_item.destroy

    respond_to do |format|
      format.html { redirect_to "http://retreat.herokuapp.com/food_committee" }
      format.json { head :no_content }
    end
  end
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/views/food_items/_form.html.erb
<%= semantic_form_for(@food_item) do |f| %>
  <% f.inputs %>
  <%= f.input :description %>
  <%= f.input :requested, :label => "How many do we need?" %>
  <%= f.actions %>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing <%= @food_item.description %></h1>

<%= render 'form' %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<h1>Listing food_items</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Requested</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @food_items.each do |food_item| %>
  <tr>
    <td><%= food_item.description %></td>
    <td><%= food_item.requested %></td>
    <td><%= link_to 'Show', food_item %></td>
    <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
    <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Food item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form' %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @food_item.description %>
</p>

<p>
  <b>Requested:</b>
  <%= @food_item.requested %>
</p>

<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>