config/routes.rb
Retreat::Application.routes.draw do

  root :to => 'families#welcome'

  resources :volunteer_tasks

  root :to => 'families#new'
  resources :food_items
  resources :food_promises

  get "food_committee/index"
  get "registrar/show"

  resources :families do
    resources :people
    collection do 
      put :paid
    end
  end

  resources :people
  
  resource :food_committee, :controller => :food_committee
  resource :retreat_committee, :controller => :retreat_committee
  resource :childcare, :controller => :childcare
  resource :registrar, :controller => :registrar
  
  get "static_pages/info"
  get "static_pages/schedule"

end

app/controllers/retreat_committee_controller.rb
class RetreatCommitteeController < ApplicationController
  def show
    @families = Family.all
    @volunteer_tasks = VolunteerTask.all
  end
end

app/views/retreat_committee/show.html.erb
<h2>Retreat Committee</h2>
<p><h3>Total numbers:</h3><br />
<b>Camping:</b>
<%= @families.map(&:camp).sum %><br />
<b>Cabin:</b>
<%= @families.map(&:cabin).sum %><br />
<b>Day (Full Weekend)</b>
<%= @families.map(&:day_full_weekend).sum %><br />
<b>Day (Partial Weekend)</b>
<%= @families.map(&:day_partial_weekend).sum %><br />

<div id="requests">
	<h3>Volunteer Tasks</h3><br />
	<i>For the sake of simplicity, this table lists only the first person from each family.</i>
<table border="1">
<th>Task</th>
<th># Pledged</th>
<th># Requested</th>
<th>Who is doing</th>
<th></th>
<% @volunteer_tasks.each do |vj| %>
  <tr>
  <td><%= vj.job_label %></td>
  <td><%= vj.volunteer_promises_count %></td>
  <td><%= vj.requested %></td>
  <td><% vj.volunteer_promises.each do |vp|%><% if vp.family %><%= vp.family.people[0].first_name %> <%= vp.family.people[0].last_name %><% end %><br /><% end %>
  <td><%= link_to 'Edit', edit_volunteer_task_path(vj) %>  <%= link_to 'Destroy', vj, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= link_to "Add volunteer task", new_volunteer_task_path %>
</div>