config/routes.rb
Retreat::Application.routes.draw do

  root :to => 'families#welcome'

  resources :volunteer_tasks

  root :to => 'families#new'
  resources :food_items
  resources :food_promises

  get "food_committee/index"
  get "registrar/show"

  resources :families do
    resources :people
    collection do 
      put :paid
    end
  end

  resources :people
  
  resource :food_committee, :controller => :food_committee
  resource :retreat_committee, :controller => :retreat_committee
  resource :childcare, :controller => :childcare
  resource :registrar, :controller => :registrar
  
  get "static_pages/info"
  get "static_pages/schedule"

end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  attr_accessible :description, :requested
  has_many :food_promises
  has_many :families, :through => :food_promises
  
end

app/controllers/registrar_controller.rb
class RegistrarController < ApplicationController
  def show
    @families = Family.all
  end
  def edit
  	@families = Family.all
  end
end

app/helpers/registrar_helper.rb
module RegistrarHelper
end

app/views/registrar/edit.html.erb
<i><p>Families listed in italics have paid</i></p>
<% @families.sort! { |a,b| a.family_name <=> b.family_name } %>
<%= form_tag paid_families_path, :method => :put do %>
  <ul> 
  	
  <% for family in @families %>
    <li>
      <% if family.paid == true %><i><% end %>
      <%= check_box_tag "family_ids[]", family.id %>
      <%= family.family_name %> (<%= family.family_folks %>) -- $<%= family.total_cost %>
      <% if family.paid == true %></i><% end %>
    </li>
    
  <% end %>
</ul>
<%= submit_tag "Mark as paid" %>
<% end %>

app/views/registrar/show.html.erb
<h1>Listing families</h1>
<h3><%= link_to 'Edit paid information', edit_registrar_path %>
<%= link_to 'New Family', new_family_path %></h3>
<table border="2">
  <tr>
    <th>Family Name</th>
    <th>People</th>
    <th>Cabin</th>
    <th>Camp</th>
    <th>Day full weekend</th>
    <th>Day partial weekend</th>
    <th>Contribution</th>
    <th>TOTAL COST</th>
    <th>Paid</th>
    
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @families.sort! { |a,b| a.family_name <=> b.family_name } %>
<% @families.each do |family| %>
  <tr>
    <td><%= family.family_name %>
    <td><%= family.family_folks %></td>
    <td><%= family.cabin %></td>
    <td><%= family.camp %></td>
    <td><%= family.day_full_weekend %></td>
    <td><%= family.day_partial_weekend %></td>
    <td><%= family.contribution %></td>
    <td><%= family.total_cost %></td>
    <td><%= family.paid %></td>   
    <td><%= link_to 'Show', family %></td>
    <td><%= link_to 'Edit', edit_family_path(family) %></td>
    <td><%= link_to 'Destroy', family, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />